import "./globals.css";

export const metadata = {
  title: "Movies in Next.js!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header> </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
